### PR TITLE
ci: Use Node 22 for action

### PR DESCRIPTION
**Pull request by bugwelle**
Node 16 is deprecated.

### CODE REVIEW

**Comment by schwma** [comment]
Thanks for the PR :)

Would you mind adding a quick entry to `CHANGELOG.md` about the version bump? If you don't have the time, I can do it as well.

**Comment by bugwelle** [comment]
@schwma Please let me know if this is how you'd like it to be. :)

**Comment by schwma** [comment]
Sorry, I don't want to create too much work for you, but could you please move the entry to the `### Changed` section under `## Version 1.1.0 - tbd` and remove the `Version 2.0.0` section?

I'll update the changelog and create the release in another PR

**Comment by bugwelle** [comment]
Done. :)

**Comment by schwma** [comment]
Great, thank you very much! :)

**Comment by schwma** [comment]
Turns out GHA didn't like that 😄

```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node22' is not supported, use 'docker', 'node12', 'node16' or 'node20' instead.')
```

https://github.com/schwma/parse-changelog-action/actions/runs/9664692021/job/26659962444

Btw, I created a release https://github.com/schwma/parse-changelog-action/releases/tag/v1.2.0, but the action to create `v1` and `latest` tags didn't run as expected. I'm trying to get those to update as well.

**Comment by schwma** [comment]
@bugwelle FYI, I manually fixed the `latest` and `v1` tags for now. They both now point to `v1.2.0`.

**Comment by bugwelle** [comment]
Thanks. Sorry about that! 😅

**Comment by schwma** [comment]
No problem! I didn't expect that either 😄

**Pull request merged**
